# Generated by Django 4.1.7 on 2023-06-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_delete_surveyresponse"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("phonenumber", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("gender", models.TextField()),
                ("age", models.IntegerField(default=0)),
                ("accent", models.TextField()),
                ("answer", models.TextField()),
                ("mbti", models.CharField(default="N/A", max_length=10)),
                ("hobby", models.TextField()),
                ("music", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
