# Generated by Django 4.1.7 on 2023-06-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_userinfo_user_is_active_user_is_admin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default="", max_length=20),
        ),
    ]
