# Generated by Django 4.1.7 on 2023-06-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_user_phone_number_alter_userinfo_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo", name="name", field=models.TextField(null=True),
        ),
    ]
