# Generated by Django 4.1.7 on 2023-06-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_userinfo_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="userinfo", name="name", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="phonenumber",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
