# Generated by Django 4.1.7 on 2023-06-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_user_password_alter_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
