# Generated by Django 4.1.7 on 2023-06-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="userinfo", name="name", field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="phonenumber",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
