# Generated by Django 4.1.7 on 2023-06-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_user_password_alter_user_phone_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="phone_number", new_name="phonenumber",
        ),
    ]
