# Generated by Django 4.1.7 on 2023-06-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_rename_phone_number_user_phonenumber"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="phonenumber", new_name="phone_number",
        ),
    ]
