# Generated by Django 4.1.7 on 2023-06-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="UserInfo",),
        migrations.AddField(
            model_name="user",
            name="accent",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="user", name="age", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="answer",
            field=models.TextField(default="None", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.TextField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="hobby",
            field=models.TextField(default="None", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="mbti",
            field=models.CharField(default="N/A", max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="music",
            field=models.TextField(default="None", max_length=20),
        ),
    ]
