# Generated by Django 4.1.7 on 2023-06-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_delete_userinfo_user_accent_user_age_user_answer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("gender", models.TextField(default="None", max_length=100)),
                ("age", models.IntegerField(default=0)),
                ("accent", models.CharField(default="None", max_length=100)),
                ("answer", models.TextField(default="None", max_length=20)),
                ("mbti", models.CharField(default="N/A", max_length=10)),
                ("hobby", models.TextField(default="None", max_length=20)),
                ("music", models.TextField(default="None", max_length=20)),
            ],
            options={"abstract": False,},
        ),
        migrations.RemoveField(model_name="user", name="accent",),
        migrations.RemoveField(model_name="user", name="age",),
        migrations.RemoveField(model_name="user", name="answer",),
        migrations.RemoveField(model_name="user", name="gender",),
        migrations.RemoveField(model_name="user", name="hobby",),
        migrations.RemoveField(model_name="user", name="mbti",),
        migrations.RemoveField(model_name="user", name="music",),
    ]
