# Generated by Django 4.1.7 on 2023-06-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_userinfo_remove_user_accent_remove_user_age_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userinfo", name="last_login",),
        migrations.RemoveField(model_name="userinfo", name="password",),
    ]
