# Generated by Django 4.1.7 on 2023-06-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_remove_userinfo_last_login_remove_userinfo_password"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
        migrations.DeleteModel(name="UserInfo",),
    ]
