# Generated by Django 4.1.7 on 2023-06-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_delete_userinfo_alter_user_q1_alter_user_q10_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="q10",),
        migrations.RemoveField(model_name="user", name="q8",),
        migrations.RemoveField(model_name="user", name="q9",),
    ]
