# Generated by Django 4.1.7 on 2023-06-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="studentID",
            field=models.IntegerField(max_length=30),
        ),
    ]
