# Generated by Django 4.1.7 on 2023-06-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_alter_student_studentid"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="is_active",),
        migrations.RemoveField(model_name="user", name="is_admin",),
        migrations.RemoveField(model_name="user", name="is_staff",),
        migrations.RemoveField(model_name="user", name="last_login",),
        migrations.RemoveField(model_name="user", name="name",),
        migrations.RemoveField(model_name="user", name="password",),
        migrations.RemoveField(model_name="user", name="phone_number",),
    ]
