# Generated by Django 4.1.7 on 2023-06-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user", name="password", field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
