# Generated by Django 4.1.7 on 2023-06-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_alter_user_name_alter_user_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("q1", models.CharField(default="", max_length=20)),
                ("q2", models.CharField(default="", max_length=20)),
                ("q3", models.CharField(default="", max_length=20)),
                ("q4", models.CharField(default="", max_length=20)),
                ("q5", models.CharField(default="", max_length=10)),
                ("q6", models.CharField(default="", max_length=10)),
                ("q7", models.CharField(default="", max_length=10)),
            ],
        ),
        migrations.RemoveField(model_name="user", name="q1",),
        migrations.RemoveField(model_name="user", name="q2",),
        migrations.RemoveField(model_name="user", name="q3",),
        migrations.RemoveField(model_name="user", name="q4",),
        migrations.RemoveField(model_name="user", name="q5",),
        migrations.RemoveField(model_name="user", name="q6",),
        migrations.RemoveField(model_name="user", name="q7",),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.TextField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default="", max_length=20, unique=True),
        ),
    ]
