# Generated by Django 4.1.7 on 2023-06-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0038_remove_user_is_staff_alter_user_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="is_active",),
        migrations.RemoveField(model_name="user", name="is_admin",),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
