# Generated by Django 4.1.7 on 2023-06-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0040_delete_userinfo_user_is_active_user_is_admin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.TextField(default="None", max_length=100)),
                ("age", models.IntegerField(default=0)),
                ("accent", models.CharField(default="None", max_length=100)),
                ("answer", models.TextField(default="None", max_length=20)),
                ("mbti", models.CharField(default="N/A", max_length=10)),
                ("hobby", models.TextField(default="None", max_length=20)),
                ("music", models.TextField(default="None", max_length=20)),
            ],
        ),
        migrations.DeleteModel(name="Student",),
        migrations.RemoveField(model_name="user", name="is_staff",),
        migrations.RemoveField(model_name="user", name="q1",),
        migrations.RemoveField(model_name="user", name="q2",),
        migrations.RemoveField(model_name="user", name="q3",),
        migrations.RemoveField(model_name="user", name="q4",),
        migrations.RemoveField(model_name="user", name="q5",),
        migrations.RemoveField(model_name="user", name="q6",),
        migrations.RemoveField(model_name="user", name="q7",),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
