# Generated by Django 4.1.7 on 2023-06-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0041_userinfo_delete_student_remove_user_is_staff_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userinfo", name="accent",),
        migrations.RemoveField(model_name="userinfo", name="age",),
        migrations.RemoveField(model_name="userinfo", name="answer",),
        migrations.RemoveField(model_name="userinfo", name="gender",),
        migrations.RemoveField(model_name="userinfo", name="hobby",),
        migrations.RemoveField(model_name="userinfo", name="mbti",),
        migrations.RemoveField(model_name="userinfo", name="music",),
        migrations.AddField(
            model_name="userinfo",
            name="q1",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="q2",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="q3",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="q4",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="q5",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="q6",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="q7",
            field=models.CharField(default="", max_length=10),
        ),
    ]
