# Generated by Django 4.1.7 on 2023-06-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0042_remove_userinfo_accent_remove_userinfo_age_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="is_active",),
        migrations.RemoveField(model_name="user", name="is_admin",),
        migrations.RemoveField(model_name="user", name="name",),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default="", max_length=20, unique=True),
        ),
    ]
