# Generated by Django 4.1.7 on 2023-06-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0043_remove_user_is_active_remove_user_is_admin_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="UserInfo",),
        migrations.RemoveField(model_name="user", name="username",),
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="q1",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="q2",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="q3",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="q4",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="q5",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="q6",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="q7",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.TextField(default="", max_length=10),
        ),
    ]
