# Generated by Django 4.1.7 on 2023-06-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0044_delete_userinfo_remove_user_username_user_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="is_active",),
        migrations.RemoveField(model_name="user", name="is_admin",),
        migrations.RemoveField(model_name="user", name="is_staff",),
        migrations.RemoveField(model_name="user", name="last_login",),
        migrations.RemoveField(model_name="user", name="password",),
        migrations.RemoveField(model_name="user", name="q1",),
        migrations.RemoveField(model_name="user", name="q2",),
        migrations.RemoveField(model_name="user", name="q3",),
        migrations.RemoveField(model_name="user", name="q4",),
        migrations.RemoveField(model_name="user", name="q5",),
        migrations.RemoveField(model_name="user", name="q6",),
        migrations.RemoveField(model_name="user", name="q7",),
        migrations.AlterField(
            model_name="user", name="name", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
    ]
