# Generated by Django 4.1.7 on 2023-06-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0045_remove_user_is_active_remove_user_is_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="q1",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="q2",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="q3",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="q4",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="q5",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="q6",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="q7",
            field=models.CharField(default="", max_length=10),
        ),
    ]
