# Generated by Django 4.1.7 on 2023-06-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0046_user_q1_user_q2_user_q3_user_q4_user_q5_user_q6_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default=2, max_length=128, verbose_name="password"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default="", max_length=20, unique=True),
        ),
    ]
