# Generated by Django 4.1.7 on 2023-06-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0047_user_last_login_user_password_alter_user_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("q1", models.CharField(default="", max_length=20)),
                ("q2", models.CharField(default="", max_length=20)),
                ("q3", models.CharField(default="", max_length=20)),
                ("q4", models.CharField(default="", max_length=20)),
                ("q5", models.CharField(default="", max_length=10)),
                ("q6", models.CharField(default="", max_length=10)),
                ("q7", models.CharField(default="", max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default="", max_length=20),
        ),
    ]
